### PR TITLE
feat!: exposing platform enum to use directly

### LINKED ISSUE #108: Platform enum not exported
The enum `Platform` is not exposed by `pin_code_fields.dart` so we can't customise it in `DialogConfig`

### LINKED ISSUE #316: Importing file to use `Platform` enum in pin code dialog config shows error
Screenshot 2023-01-27 at 12 53 16 AM

To use `Platform` enum we have to import the following file:
```dart
import 'package:pin_code_fields/src/models/platform.dart';
```
<hr />
Importing so will give the following warning:

Screenshot 2023-01-27 at 12 52 04 AM

### PR DESCRIPTION
**Pull request by OutdatedGuy**
# This PR contains BREAKING CHANGES

### Breaking Changes

- Changed enum name to `PinCodePlatform` from `Platform`
- Making `PinCodePlatform` part of `pin_code_fields` library ultimately exposing enum to direct use from import:
```dart
import 'package:pin_code_fields/pin_code_fields.dart';
```

### Changes

- Added proper docs explaining the use of values from the `PinCodePlatform` enum

resolves #316, resolves #108

### CODE REVIEW

**Comment by OutdatedGuy** [comment]
@adar2378 can you check this?

**Comment by OutdatedGuy** [comment]
@adar2378 can you check this?

**Comment by adar2378** [comment]
Thanks @OutdatedGuy , but I think this is not needed.

**Comment by OutdatedGuy** [comment]
> Thanks @OutdatedGuy , but I think this is not needed.

Yo @adar2378, please see issues #316 and #108

**Comment by adar2378** [comment]
@OutdatedGuy hmm you’re absolutely correct ✅ We will need this, is it possible to resolve the merge conflict please?

**Comment by OutdatedGuy** [comment]
@adar2378 done.

**Comment by OutdatedGuy** [comment]
@adar2378, please release `v8.0.0` after merging this PR as it contains breaking changes and cause current projects to fail after updating.

**Comment by adar2378** [comment]
ah damn I mistakenly published wrong code in a hurry. will fix

**Comment by OutdatedGuy** [comment]
@adar2378 no worries, you can retract that version from [here](https://pub.dev/packages/internet_connection_checker_plus/admin).

**Pull request merged**
