### PR TITLE
[Feature]: Add LastPin

### PR DESCRIPTION
**Pull request by Ahmadre**
Hi 👋,

this PR will integrate "last pin" functionality to the actual state.

I added "lastPin" as a parameter and initialized the controller and the initialValues with the String. If lastPin is not provided, the standard use case as always will appear.

The actual use case why I am requesting this PR is:
Bildschirmfoto 2019-12-26 um 17 11 02

### CODE REVIEW

**Comment by adar2378** [comment]
Hello, thank you for your contribution. I didn't quite get the use of "Last Pin". Could you please explain a bit? Is it like prefilling the cells without typing?  I think you can already use your own TextEditingController with this widget to do so.

**Comment by adar2378** [comment]
I am closing this as that feature can be done by using a TextEiditingController

**Comment by Ahmadre** [comment]
Hi @adar2378  sorry for answering late, was in my holidays with my girlfriend. 

It's a pity, the use of the controller doesn't work. If the package is initialized my code isn't there. Just If I tap on the textfield my saved code will appear:
Bildschirmfoto 2019-12-27 um 16 06 32

To explain you that: I have a setting in my project, where the user can save a Pin-Code for locking the app on next startup. And here in settings the user can change his pin code for unlocking. For that I need definetly that the controllers value is same as my controllers value. I tried that as mentioned above, but it doesn't work

**Comment by Ahmadre** [comment]
I also recognized that If I debug the package ```_assignController()``` is not called on init

**Comment by Ahmadre** [comment]
But yes this PR can definetly be closed if that controller parameter works :). Thanks again!

**Comment by Ahmadre** [comment]
Ok, I found the problem:

```dart
    _textEditingController.addListener(() {
      ...

      _setTextToInput(...);
    });
```

```_setTextToInput()``` is JUST called in listener and not initial if the package will initialize. Could you fix that?

**Comment by adar2378** [comment]
> Hi @adar2378 sorry for answering late, was in my holidays with my girlfriend.
> 
> It's a pity, the use of the controller doesn't work. If the package is initialized my code isn't there. Just If I tap on the textfield my saved code will appear:
> Bildschirmfoto 2019-12-27 um 16 06 32
> 
> To explain you that: I have a setting in my project, where the user can save a Pin-Code for locking the app on next startup. And here in settings the user can change his pin code for unlocking. For that I need definetly that the controllers value is same as my controllers value. I tried that as mentioned above, but it doesn't work
Hello Ahmed, thanks for your reply. I saw your like on my comment and I thought your issue got resolved. 

I think you can add text to the controller after the ui is initialized by using `WidgetsBinding.instance
        .addPostFrameCallback((_) => yourFunction(context));` this. Then it will set the ui first, afterward it should add the code to the cells, don't forget to call it from inside of init method of that screen. Let me know if it solves your problem.

**Comment by adar2378** [comment]
And meanwhile, I'll look at the code to solve it asap.

**Comment by Ahmadre** [comment]
Okay! It's working now :) thank you for your suggestion! Solved it. 👍

**Pull request closed without merging**
