### PR TITLE
 fix issue #237

### PR DESCRIPTION
**Pull request by Add00w**
Fixes issue #237 by adding an optional TextDirection and margin to add margins from left and/or right for example.

@adar2378

### CODE REVIEW

**Comment by adar2378** [comment]
Thanks I will test it before merging.

**Comment by Add00w** [comment]
> Thanks I will test it before merging.

Take your time  👍.

**Comment by ishmeetnarula** [comment]
@adar2378 can you please merge it. I also have same issue.

**Comment by Add00w** [comment]
> @adar2378 can you please merge it. I also have same issue.

Hi @ishmeetnarula for temporary use this fix like this
```
pin_code_fields:
    git:
      url: https://github.com/Add00w/pin_code_fields.git
      ref: feature/fix237
```

**Pull request merged**
