### PR TITLE
Added scrollPadding property

### PR DESCRIPTION
**Pull request by XuanHanTan**
scrollPadding property is a property of TextFields and TextFormFields

### CODE REVIEW

**Comment by adar2378** [comment]
Hi @XuanHanTan , I want to thank you for your contribution. But unfortunately, as the TextFormField stays hidden, so adding scrollpadding doesn't have any use here.

**Comment by XuanHanTan** [comment]
Hi, may I know how we can add a scrollPadding to the PinCodeField widget
then?

**Comment by adar2378** [comment]
I think we don't need scrollPadding since this package only shows one character per field. If the box size is bigger than the font size then it is good to go. But if someone really needs ScrollPadding then s/he will have to implement by themselves from scratch.

**Comment by XuanHanTan** [comment]
Okay, thanks for your response!

**Pull request closed without merging**
