### PR TITLE
style: add text styles to the alert dialog while pasting the code

### PR DESCRIPTION
**Pull request by RehamZaky**

### CODE REVIEW

**Comment by moazelsawaf** [comment]
LGTM 🚀

**Comment by adar2378** [comment]
Will check and merge thanks 🙏

**Comment by adar2378** [comment]
I have plan to maybe remove this functionality and use default paste option per platform for textfield.

**Comment by moazelsawaf** [comment]
@adar2378 
I agree with you, the native look and feel is better.

**Pull request closed without merging**
