### PR TITLE
Fixed a bug when setState is being called after dispose()

### PR DESCRIPTION
**Pull request by JSBmanD**
It's a PR for the issue https://github.com/adar2378/pin_code_fields/issues/143

### CODE REVIEW

**Comment by adar2378** [comment]
Thanks <3

**Comment by x302502** [comment]
Im get error the same :(

**Comment by AnhDTN** [comment]
Im get the same error when using pin text fields in pagerview :(

**Comment by adar2378** [comment]
The latest version contains the fix. Please upgrade to 6.1.0

89705a8f4629e79e87a4eb963fed6bd6d1b0e7cd

**Pull request merged**
