### PR TITLE
Fix setState() called after dispose() Issue

### PR DESCRIPTION
**Pull request by shaurya-src**
fixed issue where setState() was being called through listener even after the Widget was unmounted.

### CODE REVIEW

**Comment by shaurya-src** [comment]
Fixed Issue: https://github.com/adar2378/pin_code_fields/issues/302

**Comment by adar2378** [comment]
Let’s create local _setState method that will check mounted = true before calling actual setState

**Comment by adar2378** [comment]
Thanks for contributing

**Comment by shaurya-src** [comment]
Added the local method to check mounted before setting state

**Comment by shaurya-src** [comment]
@adar2378 Can you please review this PR and make a release with these changes?

**Comment by adar2378** [comment]
Thanks!

**Pull request merged**
