### PR TITLE
New colors, optional focusNode. Keyboard fix

### PR DESCRIPTION
**Pull request by EmmanuelVlad**
**Added:**
- Colors:
  - `selectedColor` is the color set on the current index. Default is `Colors.blue`
  - `disabledColor` is the color if the TextField is disabled. Default is `Colors.grey`
- Optional `focusNode` can be passed to the constructor to manage it from outside.
  - Added a listener to the focusNode which triggers a rebuild on every change so it'll reflect the correct color on each pin.

**Fixed:**
- Colors:
  - `activeColor` and `inactiveColor` were swapped
- Keyboard does not show up onTap #4  
  - Fixed by replacing `enabled: false` to a function that check if `currentText` is null

new colors

### CODE REVIEW

**Comment by adar2378** [comment]
I'll check it soon and merge it. Thank you so much!

**Comment by EmmanuelVlad** [comment]
Great!

I've also added the features requested on #9.

I think we should rename `currentText` to `onChange` and shouldn't be required anymore, what do you think?

**Comment by adar2378** [comment]
> Great!
> 
> I've also added the features requested on #9.
> 
> I think we should rename `currentText` to `onChange` and shouldn't be required anymore, what do you think?
> 
> I'm working on a fix of a bug I've introduced in last push when pasting a text...

Yeah, onChange goes better with onComplete. You've done an amazing job. What is the bug you're facing?

**Comment by EmmanuelVlad** [comment]
> > Great!
> > I've also added the features requested on #9.
> > I think we should rename `currentText` to `onChange` and shouldn't be required anymore, what do you think?
> > I'm working on a fix of a bug I've introduced in last push when pasting a text...
> 
> Yeah, onChange goes better with onComplete. You've done an amazing job. What is the bug you're facing?

Thank you!
I've wrote about issue I'm encountering here: #13

**Pull request merged**
