### PR TITLE
Add hint/placeholder feature

### PR DESCRIPTION
**Pull request by adrianFarkas**
In this PR i added a feature to be able to set a hint or placeholder for the fields.

resolves: #161  #82 

https://user-images.githubusercontent.com/45693911/118806281-2a14fd80-b8a7-11eb-826e-15a45b0817df.mov

### CODE REVIEW

**Comment by adar2378** [comment]
Looking great! Thank you @adrianFarkas I will check and merge it soon.

**Comment by didifend** [comment]
Hi All,

image

How can I put a different hint character in each field like this?
Please, help me @adrianFarkas.

Thank u

**Comment by adrianFarkas** [comment]
It's not really possible with this implementation

**Comment by didifend** [comment]
@adrianFarkas 

Oh okay, while I put 2 fields, first for placeholders (readonly) and second for input fields which have transparent fill color. It work for me. Hope, next version possible for this implementation.

Thank u

**Pull request merged**
