### PR TITLE
added the Shadow in pincode

### LINKED ISSUE #83: Be able to add box shadow in field decoration container
Hello i want to be able to add box shadow int the `decoration property of AnimatedContainer in the _generateFields` can you expose a boxshadow property in the pinTheme?

### PR DESCRIPTION
**Pull request by mohak852**
fixes #83 @adar2378 I have added the box-shadow field decoration container

### CODE REVIEW

**Review by adar2378 — CHANGES_REQUESTED** [review]
Hi, great work! Thank you so much. I think rather than taking shadows ourselves, we should rather let users input a list of drop shadows.  boxShadow: widget.shadows or something like this,

**Comment by mohak852** [comment]
@adar2378 I have added the shadow.

**Comment by adar2378** [comment]
Okay, I'll see if this fits properly. Thanks <3

**Comment by mohak852** [comment]
@adar2378 If you reviewed the PR you can merge this PR

**Comment by adar2378** [comment]
Oh sorry, I totally forgot to tell you about this, I think it should be an array of BoxShadow's that the user should input rather than inputting a single one. `boxShadow: widget.shadows` similar to this.

**Comment by mohak852** [comment]
@adar2378 I cant able to understand what do you mean by an array of boxshadow's can you please briefly expand this and explain me more about it?

**Comment by adar2378** [comment]
Yeah, think of it like a normal `Container`. How do we add shadows in normal `Container`? We had a list of `BoxShadow`. It should be the same for the pinfields I think.

The code you wrote, it only passes one BoxShadow, not a list of BoxShadow

**Comment by mohak852** [comment]
I have added the list of shaow you can check @adar2378

**Pull request merged**
